apiVersion: apps/v1
kind: Deployment
metadata:
  name: bees
  labels:
    version: 1.0.0
spec:
  selector:
    matchLabels:
      app: bees
  template:
    metadata:
      labels:
        app: bees
        version: 1.0.0
    spec:
      initContainers:
        - name: init-agent
          image: apache/skywalking-base:8.1.0-es7
          command: ["cp", "-r", "/skywalking/agent", "/opt/copy"]
          volumeMounts:
            - name: agent
              mountPath: /opt/copy
      containers:
        - name: bees
          image: itmabo/bees:v1.0.0
          imagePullPolicy: Always
          env:
            - name: SW_AGENT_NAME
              value: bees
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: oap:11800
          ports:
            - name: main-port
              containerPort: 8080
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: agent
              mountPath: /opt/agent/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: bees
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: main-port
  selector:
    app: bees
