FROM openjdk:8-jre-alpine

LABEL maintainer="ittony.ma@gmail.com"

ENV JAVA_OPTS=

ARG JAR_FILE=sky/target/*.jar

ADD ${JAR_FILE} /app.jar

CMD ["java", ${JAVA_OPTS} ,"-Xmx1024m", "-XX:-UseGCOverheadLimit", "-jar", "/app.jar"]

EXPOSE 8080
