apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: main-port
  selector:
    app: skywalking-ui
