apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-ui
  labels:
    version: 1.0.0
spec:
  selector:
    matchLabels:
      app: skywalking-ui
  template:
    metadata:
      labels:
        app: skywalking-ui
        version: 1.0.0
    spec:
      containers:
        - name: skywalking-ui
          image: apache/skywalking-ui:8.1.0
          imagePullPolicy: Always
          ports:
            - name: main-port
              containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "1000Mi"
            limits:
              cpu: "900m"
              memory: "1500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: main-port
  selector:
    app: skywalking-ui

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: skywalking-ui
  namespace: istio-system
spec:
  hosts:
    - skywalking.tb1.sayweee.net
  gateways:
    - ingressgateway.istio-system.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: skywalking-ui.defualt.svc.culster.local
            port:
              number: 8080